<a href="https://colab.research.google.com/github/mukunth-kart/OpenCV_LS/blob/main/Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


#**Problem 1**

In [ ]:
arr = np.random.randint(0, 256, size = (15,15))
arr

array([[189, 217,  96, 174, 129, 219,  26,  41, 101,  59, 129, 104, 204,
        221, 109],
       [ 19,  92,  77, 193, 178, 226,  50,  45,  51,  48, 230, 167, 152,
        122,  71],
       [ 13,  46,  19, 124, 152,  88,  70, 143,  28,  41,   7,   9, 212,
        249, 132],
       [ 69, 190, 132,  61,   6, 224,  91, 239, 211,  90,  76, 221,  48,
        137,  40],
       [234,  94, 131,  65,  89, 196, 215, 181, 222, 209,  61, 169,  44,
         54, 180],
       [204, 222,  24, 112,   8,  14, 252, 193,  27, 118, 146, 149,  84,
        192,  36],
       [141,  44, 235,  83,  35, 119, 252, 255, 193, 101,  44,  11,  94,
        234, 231],
       [  3, 159,  88,  40,   6, 140, 118,  16,  87, 106,   9, 228,  44,
          5, 155],
       [ 51, 204, 193, 130, 157, 193,  35, 127,  48, 210, 143,  81, 138,
         26, 166],
       [126,  70,  70, 254,  25,  65, 103, 134, 201, 164, 251,  90,  79,
         30,   3],
       [  5, 220,  28,  35,  95,  35,  52,  63, 119,  25,   6, 225,  53,
       

1. Create a new array where all the elements less than the threshold(120) are set to zero and the
rest of them remain the same.

In [ ]:
new_arr = list()
for i in arr:
  for j in range(len(i)):
    if(i[j]<120):
      i[j] = 0
  new_arr.append(i)
new_arr = np.array(new_arr)

In [ ]:
new_arr

array([[189, 217,   0, 174, 129, 219,   0,   0,   0,   0, 129,   0, 204,
        221,   0],
       [  0,   0,   0, 193, 178, 226,   0,   0,   0,   0, 230, 167, 152,
        122,   0],
       [  0,   0,   0, 124, 152,   0,   0, 143,   0,   0,   0,   0, 212,
        249, 132],
       [  0, 190, 132,   0,   0, 224,   0, 239, 211,   0,   0, 221,   0,
        137,   0],
       [234,   0, 131,   0,   0, 196, 215, 181, 222, 209,   0, 169,   0,
          0, 180],
       [204, 222,   0,   0,   0,   0, 252, 193,   0,   0, 146, 149,   0,
        192,   0],
       [141,   0, 235,   0,   0,   0, 252, 255, 193,   0,   0,   0,   0,
        234, 231],
       [  0, 159,   0,   0,   0, 140,   0,   0,   0,   0,   0, 228,   0,
          0, 155],
       [  0, 204, 193, 130, 157, 193,   0, 127,   0, 210, 143,   0, 138,
          0, 166],
       [126,   0,   0, 254,   0,   0,   0, 134, 201, 164, 251,   0,   0,
          0,   0],
       [  0, 220,   0,   0,   0,   0,   0,   0,   0,   0,   0, 225,   0,
       

2. Create a Python function named boundary transversal(matrix) that will print out boundary
elements of the matrix starting from the top-left corner and in clockwise direction.


In [ ]:
def boundary_transversal(matrix):
  ulim = len(matrix)-1
  llim = 0
  mid_elem = matrix[int(ulim/2)][int(ulim/2)]
  l = list()
  i = 0
  j = 0
  even = True #even x even
  if(ulim%2==0):
    even = False #odd x odd
  while(True):
    i = llim
    j = llim
    while(True):
      l.append(matrix[i][j])
      j+=1
      if(j==ulim):
        break
    while(True):
      l.append(matrix[i][j])
      i+=1
      if(i==ulim):
        break
    while(True):
      l.append(matrix[i][j])
      j-=1
      if(j==llim):
        break
    while(True):
      if(i!=llim):
        l.append(matrix[i][j])
      i-=1
      if(i==llim):
        break
    ulim-=1
    llim+=1
    if(llim>=ulim):
      break
  if(even == False): # If odd x odd matrix then add middle number seperately
    l.append(mid_elem)
  return l


3. Create a new Numpy array by replacing all the odd elements with zero and even with one.

In [ ]:
odd_even = list()
for i in arr:
  for j in range(len(i)):
    if(i[j]%2 == 0):
      i[j] = 1
    else:
      i[j] = 0
  odd_even.append(i)
odd_even = np.array(odd_even)

In [ ]:
odd_even

array([[0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1]])